version: '3'
services:
  nginx:
    image: nginx:1.25.1
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - ./nginx/glassfish.conf:/etc/nginx/conf.d/default.conf

  glassfish:
    image: glassfish:latest
    ports:
      - 4848:4848
    volumes:
      - ./dist/keystore/cacerts.jks:/java/glassfish4/glassfish/domains/askd/config/cacerts.jks
      - ./dist/keystore/keystore.jks:/java/glassfish4/glassfish/domains/askd/config/keystore.jks
