version: '3'
services:
  nginx:
    image: nginx:1.25.1
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - ./nginx/glassfish.conf:/etc/nginx/conf.d/default.conf

  glassfish:
    image: askd:test
    ports:
      - 4848:4848
    #volumes:
    #  - ./glassfish:/java/glassfish4/glassfish/domains/askd
